openapi: 3.0.1
info:
  title: Client to a service which injects faults and delays
  description: |
    Client to a service which injects faults and delays
  version: 1.0.0
servers:
  - url: http://localhost:8081
tags:
  - name: messages
paths:
  /caller/messages:
    post:
      tags:
        - messages
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessageRequest'
      responses:
        200:
          description: Message Acknowledgement
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageAck'
components:
  schemas:
    MessageRequest:
      type: object
      properties:
        id:
          type: string
          example: an-id
        payload:
          type: string
        delay:
          type: integer
          default: 0
          description: delay in milliseconds
        responseCode:
          type: integer
          default: 200
          description: response code to be plugged in by the producer

    MessageAck:
      type: object
      properties:
        id:
          type: string
        received:
          type: string
        callerHeaders:
          $ref: '#/components/schemas/Headers'
        producerHeaders:
          $ref: '#/components/schemas/Headers'
        callerMetadata:
          $ref: '#/components/schemas/ClusterMetadata'
        producerMetadata:
          $ref: '#/components/schemas/ClusterMetadata'
        roundTripTimeMillis:
          type: number
          description: Round trip time in milliseconds
        statusCode:
          type: number
          description: http status code of response from the producer
    ClusterMetadata:
      type: object
      properties:
        clusterName:
          type: string
        clusterLocation:
          type: string
    Headers:
      type: object