steps:
  - name: openjdk:11
    id: test
    entrypoint: "/bin/bash"
    args:
      - '-c'
      - |-
        set -x
        ./gradlew -p sample-caller check
        ./gradlew -p sample-producer check

  - name: openjdk:11
    id: build-image
    entrypoint: "/bin/bash"
    args:
      - '-c'
      - |-
        set -x
        ./gradlew -p sample-caller jib --image=us-west1-docker.pkg.dev/$PROJECT_ID/sample-repo/sample-caller:$SHORT_SHA
        ./gradlew -p sample-producer jib --image=us-west1-docker.pkg.dev/$PROJECT_ID/sample-repo/sample-producer:$SHORT_SHA