steps:
  - name: openjdk:11
    id: test
    entrypoint: "/bin/bash"
    args:
      - '-c'
      - |-
        set -x
        ./gradlew -p sample-caller check
        ./gradlew -p sample-producer check

  - name: openjdk:11
    id: build-image
    entrypoint: "/bin/bash"
    args:
      - '-c'
      - |-
        set -x
        ./gradlew -p sample-caller jib --image=us-docker.pkg.dev/$PROJECT_ID/docker-repo/sample-caller:$SHORT_SHA -Djib.to.tags="latest"
        ./gradlew -p sample-producer jib --image=us-docker.pkg.dev/$PROJECT_ID/docker-repo/sample-producer:$SHORT_SHA -Djib.to.tags="latest"