apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: sample-service-to-service
build:
  artifacts:
    - image: sample-caller-image
#      context: sample-caller
      jib:
        type: gradle
        project: sample-caller
    - image: sample-producer-image
#      context: sample-producer
      jib:
        type: gradle
        project: sample-producer

deploy:
  kubectl:
    manifests:
      - sample-caller/kube/sample-caller-kube.yaml
      - sample-producer/kube/sample-producer-kube.yaml
#profiles:
#  - name: mesh
#    deploy:
#      kubectl:
#        manifests:
#          - sample-caller/kube/sample-caller-kube.yaml
#          - sample-caller/istio/sample-caller-destination-rule.yaml
#          - sample-caller/istio/sample-caller-gateway.yaml
#          - sample-producer/istio/sample-producer-destination-rule.yaml
#          - sample-producer/istio/sample-producer-vs.yaml
