apiVersion: networking.gke.io/v1
kind: MultiClusterIngress
metadata:
  name: sample-caller-ingress
  namespace: istio-apps
spec:
  template:
    spec:
      backend:
        serviceName: sample-caller-mcs
        servicePort: 8080