---
server:
  port: 8081

logging:
  level:
    root: info

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

remote:
  base:
    url: "http://localhost:8080"