---
server:
  port: 8080

logging:
  level:
    root: info

spring:
  main:
    lazy-initialization: true
management:
  endpoint:
    health:
      enabled: true
      show-details: always
      probes:
        enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "*"

remote:
  base:
    url: "http://sample-producer:8080"
