openapi: 3.0.1
info:
  title: Service injecting faults and delays
  description: |
    Service which injects faults and delays
  version: 1.0.0
servers:
  - url: http://localhost:8080
tags:
  - name: messages
paths:
  /producer/messages:
    post:
      tags:
        - messages
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessageRequest'
      responses:
        200:
          description: Message Acknowledgement
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageAck'
components:
  schemas:
    MessageRequest:
      type: object
      properties:
        id:
          type: string
          example: an-id
        payload:
          type: string
        delay:
          type: integer
          default: 0
          description: delay in milliseconds
        responseCode:
          type: integer
          default: 200
          description: response code to be plugged in by the producer

    MessageAck:
      type: object
      properties:
        id:
          type: string
        received:
          type: string
        ack:
          type: string