apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: sample-producer
build:
  artifacts:
    - image: sample-producer-image
      jib:
        type: gradle
deploy:
  kubectl:
    manifests:
      - kube/sample-producer-kube.yaml
profiles:
  - name: mesh
    deploy:
      kubectl:
        manifests:
          - kube/sample-producer-kube.yaml
          - istio/sample-producer-destination-rule.yaml