apiVersion: v1
kind: Service
metadata:
  name: sample-producer
  labels:
    app: sample-producer
    service: sample-producer
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: sample-producer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sample-producer-sa
  labels:
    account: sample-producer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-producer-v1
  labels:
    app: sample-producer
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-producer
      version: v1
  template:
    metadata:
      labels:
        app: sample-producer
        version: v1
    spec:
      serviceAccountName: sample-producer-sa
      containers:
        - name: sample-producer
          image: us-docker.pkg.dev/biju-altostrat-demo/docker-repo/sample-producer:f8f984b
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          securityContext:
            runAsUser: 1000
          resources:
            requests:
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080