---
server:
  port: 8080

logging:
  level:
    root: info

management:
  health:
    probes:
      enabled: true
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "*"
